### ISSUE TITLE
Re-entrance Error.

### ISSUE THREAD

**Issue by Blntswrd** [BrassAmber-Mods/soulbound-armory#8]
When trying to run 3.1.0 alpha the game crashes with a re-entrance error.
[2022-11-05-2.log](https://github.com/BrassAmber-Mods/soulbound-armory/files/9943007/2022-11-05-2.log)

**Comment by nnym** [comment]
It runs without any other mods so I figure that another mod's presence makes this error possible. The log does not contain enough information for me to pinpoint any mod that is related to this issue though; but no matter for I have an alternative better solution in mind.

**Comment by nnym** [comment]
I've released version [3.2.0](https://www.curseforge.com/minecraft/mc-mods/soulbound-armory/files/4073285) which might fix this issue. Mind the changelog: there's a breaking change.

**Comment by Blntswrd** [comment]
Added it back to the modpack I'm using at it crashed again with this:
[crash-2022-11-07_22.24.05-fml.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/9957351/crash-2022-11-07_22.24.05-fml.txt)
Full log:
[latest.log](https://github.com/BrassAmber-Mods/soulbound-armory/files/9957353/latest.log)

**Comment by nnym** [comment]
Does it run if you don't have any other mods?

**Comment by nnym** [comment]
If you're using a JRE only, then you might have to try using a JDK.

**Comment by Blntswrd** [comment]
It does not run if it's by itself. 
[crash-2022-11-08_10.45.24-fml.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/9962851/crash-2022-11-08_10.45.24-fml.txt)
[latest.log](https://github.com/BrassAmber-Mods/soulbound-armory/files/9962853/latest.log)

**Comment by nnym** [comment]
[Version 3.2.1](https://www.curseforge.com/minecraft/mc-mods/soulbound-armory/files/4081647) should fix this problem.

**Comment by Blntswrd** [comment]
It now runs by itself but still won't run with ATM8. I can't give a log because no error generates. It just crashes back to the launcher before Minecraft pops up.

**Comment by nnym** [comment]
I've published [another fix](https://www.curseforge.com/minecraft/mc-mods/soulbound-armory/files/4084710).

**Comment by Blntswrd** [comment]
Works and loads into the world. Thank you.

**Comment by nnym** [comment]
Thanks for testing the mod.
